name: Compiling and Run Unit Tests on Ubuntu 24.04
on:
  pull_request:
    branches: [master]

env:
  NINJA_VERSION: 1.12.1
  CCACHE_VERSION: 4.10.2
  COMPILING_TOOLS_DIR: "~/.tools"

jobs:
  build-unit-tests:
    name: "ubuntu-24.04-${{ matrix.compiler }}-${{ matrix.version }}"
    runs-on: ubuntu-24.04
    strategy:
      fail-fast: false
      matrix:
        include:
          # Details: https://github.com/actions/runner-images
          - { compiler: "gcc",   version: "12.3.0" }
          - { compiler: "gcc",   version: "14.2.0" }
          - { compiler: "clang", version: "16.1.6" }
          - { compiler: "clang", version: "18.1.3" }

    steps:
      - name: Get Current Time
        id: time
        run: |
          timestamp=$(date +"%Y-%m-%d %H:%M:%S")
          echo ${timestamp}
          echo "timestamp=${timestamp}" >> ${GITHUB_OUTPUT}

      - name: Cache and Restore Compiling Tools
        id: compiling-tools-cache
        uses: actions/cache@v4
        with:
          path: ${COMPILING_TOOLS_DIR}
          key: compiling-tools-${{ runner.os }}
          restore-keys: compiling-tools-${{ runner.os }}

      - name: Install Compiling Tools
        # if: "${{ steps.cache-compiling-tools.outputs.cache-hit == false }}"
        run: |
          bash ./.github/workflows/install_compiling_tools.sh

      - name: Install Libraries
        run:  sudo apt-get install -y libboost-all-dev libgit2-dev

      - name: Setup C/C++ Compiler and ccache
        run: |
          set -euo pipefail
          major=$(echo ${{ matrix.version }} | cut -d'.' -f1)
          if [[ "${{ matrix.compiler }}" == "clang" ]]; then
            echo "CC=clang-${major}" >> ${GITHUB_ENV}
            echo "CXX=clang++-${major}" >> ${GITHUB_ENV}
          else
            echo "CC=gcc-${major}" >> ${GITHUB_ENV}
            echo "CXX=g++-${major}" >> ${GITHUB_ENV}
          fi

          ccache --version
          ccache --set-config=max_size=500M

      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          submodules: true

      - name: Cache and Restore ccache
        id: ccache-cache
        uses: actions/cache@v4
        with:
          path: ~/.ccache
          key: ccache-${{ matrix.compiler }}-${{ matrix.version }}-${{ steps.time.outputs.timestamp }}
          restore-keys: ccache-${{ matrix.compiler }}-${{ matrix.version }}-

      - name: Create Build Directory
        run: mkdir -p build

      - name: Cache and Restore CMake FetchContent
        id: fetchcontent-cache
        uses: actions/cache@v4
        with:
          path: build/_deps/
          key: fetchcontent-${{ matrix.compiler }}-${{ matrix.version }}-${{ steps.time.outputs.timestamp }}
          restore-keys: fetchcontent-${{ matrix.compiler }}-${{ matrix.version }}-

      - name: Compile
        run: |
          set -euo pipefail
          cmake -S . -B build -GNinja              \
            -DCMAKE_BUILD_TYPE=Release             \
            -DCMAKE_C_COMPILER_LAUNCHER=ccache     \
            -DCMAKE_CXX_COMPILER_LAUNCHER=ccache

          cmake --build build -v -j`nproc`
          ccache -s -v

      - name: Run Unit Tests
        run: ./build/tests/test
